TEMPLATE = app
CONFIG += console c++11

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
INCLUDEPATH +=./include ./thirdparty/include

LIBS += -L$$PWD/thirdparty/libs \
        -lavformat -lavcodec -lavutil -lswscale -lswresample -lx264 -ljpeg\
        -lssl -lsrs_rtmp -lcrypto \
        -lSDL2main -lSDL2 -lz -ldl -lpthread -llzma -lm

SOURCES += \
    source/context_frames.cpp \
    source/ip_camera.cpp \
    source/multi_context_frames.cpp \
    source/multi_video_service.cpp \
    source/public_function.cpp \
    source/video_decode.cpp \
    source/video_encode.cpp \
    source/video_manager.cpp \
    samples/sample_show_video.cpp \
    samples/mainwindow.cpp

DISTFILES += \
    configs/config1.json \
    configs/config5.json \
    CMakeLists.txt \
    configs/config12.json

HEADERS += \
    include/multi_video_service.h \
    include/multi_video_service_define.h \
    samples/public_function.hpp \
    source/context_frames.h \
    source/ip_camera.h \
    source/multi_context_frames.h \
    source/public_function.h \
    source/video_decode.h \
    source/video_encode.h \
    source/video_manager.h \
    thirdparty/include/libavcodec/ac3_parser.h \
    thirdparty/include/libavcodec/adts_parser.h \
    thirdparty/include/libavcodec/avcodec.h \
    thirdparty/include/libavcodec/avdct.h \
    thirdparty/include/libavcodec/avfft.h \
    thirdparty/include/libavcodec/d3d11va.h \
    thirdparty/include/libavcodec/dirac.h \
    thirdparty/include/libavcodec/dv_profile.h \
    thirdparty/include/libavcodec/dxva2.h \
    thirdparty/include/libavcodec/jni.h \
    thirdparty/include/libavcodec/mediacodec.h \
    thirdparty/include/libavcodec/qsv.h \
    thirdparty/include/libavcodec/vaapi.h \
    thirdparty/include/libavcodec/vda.h \
    thirdparty/include/libavcodec/vdpau.h \
    thirdparty/include/libavcodec/version.h \
    thirdparty/include/libavcodec/videotoolbox.h \
    thirdparty/include/libavcodec/vorbis_parser.h \
    thirdparty/include/libavcodec/xvmc.h \
    thirdparty/include/libavdevice/avdevice.h \
    thirdparty/include/libavdevice/version.h \
    thirdparty/include/libavfilter/avfilter.h \
    thirdparty/include/libavfilter/avfiltergraph.h \
    thirdparty/include/libavfilter/buffersink.h \
    thirdparty/include/libavfilter/buffersrc.h \
    thirdparty/include/libavfilter/version.h \
    thirdparty/include/libavformat/avformat.h \
    thirdparty/include/libavformat/avio.h \
    thirdparty/include/libavformat/version.h \
    thirdparty/include/libavutil/adler32.h \
    thirdparty/include/libavutil/aes.h \
    thirdparty/include/libavutil/aes_ctr.h \
    thirdparty/include/libavutil/attributes.h \
    thirdparty/include/libavutil/audio_fifo.h \
    thirdparty/include/libavutil/avassert.h \
    thirdparty/include/libavutil/avconfig.h \
    thirdparty/include/libavutil/avstring.h \
    thirdparty/include/libavutil/avutil.h \
    thirdparty/include/libavutil/base64.h \
    thirdparty/include/libavutil/blowfish.h \
    thirdparty/include/libavutil/bprint.h \
    thirdparty/include/libavutil/bswap.h \
    thirdparty/include/libavutil/buffer.h \
    thirdparty/include/libavutil/camellia.h \
    thirdparty/include/libavutil/cast5.h \
    thirdparty/include/libavutil/channel_layout.h \
    thirdparty/include/libavutil/common.h \
    thirdparty/include/libavutil/cpu.h \
    thirdparty/include/libavutil/crc.h \
    thirdparty/include/libavutil/des.h \
    thirdparty/include/libavutil/dict.h \
    thirdparty/include/libavutil/display.h \
    thirdparty/include/libavutil/downmix_info.h \
    thirdparty/include/libavutil/encryption_info.h \
    thirdparty/include/libavutil/error.h \
    thirdparty/include/libavutil/eval.h \
    thirdparty/include/libavutil/ffversion.h \
    thirdparty/include/libavutil/fifo.h \
    thirdparty/include/libavutil/file.h \
    thirdparty/include/libavutil/frame.h \
    thirdparty/include/libavutil/hash.h \
    thirdparty/include/libavutil/hmac.h \
    thirdparty/include/libavutil/hwcontext.h \
    thirdparty/include/libavutil/hwcontext_cuda.h \
    thirdparty/include/libavutil/hwcontext_d3d11va.h \
    thirdparty/include/libavutil/hwcontext_drm.h \
    thirdparty/include/libavutil/hwcontext_dxva2.h \
    thirdparty/include/libavutil/hwcontext_mediacodec.h \
    thirdparty/include/libavutil/hwcontext_qsv.h \
    thirdparty/include/libavutil/hwcontext_vaapi.h \
    thirdparty/include/libavutil/hwcontext_vdpau.h \
    thirdparty/include/libavutil/hwcontext_videotoolbox.h \
    thirdparty/include/libavutil/imgutils.h \
    thirdparty/include/libavutil/intfloat.h \
    thirdparty/include/libavutil/intreadwrite.h \
    thirdparty/include/libavutil/lfg.h \
    thirdparty/include/libavutil/log.h \
    thirdparty/include/libavutil/lzo.h \
    thirdparty/include/libavutil/macros.h \
    thirdparty/include/libavutil/mastering_display_metadata.h \
    thirdparty/include/libavutil/mathematics.h \
    thirdparty/include/libavutil/md5.h \
    thirdparty/include/libavutil/mem.h \
    thirdparty/include/libavutil/motion_vector.h \
    thirdparty/include/libavutil/murmur3.h \
    thirdparty/include/libavutil/opt.h \
    thirdparty/include/libavutil/parseutils.h \
    thirdparty/include/libavutil/pixdesc.h \
    thirdparty/include/libavutil/pixelutils.h \
    thirdparty/include/libavutil/pixfmt.h \
    thirdparty/include/libavutil/random_seed.h \
    thirdparty/include/libavutil/rational.h \
    thirdparty/include/libavutil/rc4.h \
    thirdparty/include/libavutil/replaygain.h \
    thirdparty/include/libavutil/ripemd.h \
    thirdparty/include/libavutil/samplefmt.h \
    thirdparty/include/libavutil/sha.h \
    thirdparty/include/libavutil/sha512.h \
    thirdparty/include/libavutil/spherical.h \
    thirdparty/include/libavutil/stereo3d.h \
    thirdparty/include/libavutil/tea.h \
    thirdparty/include/libavutil/threadmessage.h \
    thirdparty/include/libavutil/time.h \
    thirdparty/include/libavutil/timecode.h \
    thirdparty/include/libavutil/timestamp.h \
    thirdparty/include/libavutil/tree.h \
    thirdparty/include/libavutil/twofish.h \
    thirdparty/include/libavutil/version.h \
    thirdparty/include/libavutil/xtea.h \
    thirdparty/include/libswresample/swresample.h \
    thirdparty/include/libswresample/version.h \
    thirdparty/include/libswscale/swscale.h \
    thirdparty/include/libswscale/version.h \
    thirdparty/include/libjpeg/jconfig.h \
    thirdparty/include/libjpeg/jerror.h \
    thirdparty/include/libjpeg/jmorecfg.h \
    thirdparty/include/libjpeg/jpeglib.h \
    thirdparty/include/rapidjson/error/en.h \
    thirdparty/include/rapidjson/error/error.h \
    thirdparty/include/rapidjson/internal/biginteger.h \
    thirdparty/include/rapidjson/internal/diyfp.h \
    thirdparty/include/rapidjson/internal/dtoa.h \
    thirdparty/include/rapidjson/internal/ieee754.h \
    thirdparty/include/rapidjson/internal/itoa.h \
    thirdparty/include/rapidjson/internal/meta.h \
    thirdparty/include/rapidjson/internal/pow10.h \
    thirdparty/include/rapidjson/internal/regex.h \
    thirdparty/include/rapidjson/internal/stack.h \
    thirdparty/include/rapidjson/internal/strfunc.h \
    thirdparty/include/rapidjson/internal/strtod.h \
    thirdparty/include/rapidjson/internal/swap.h \
    thirdparty/include/rapidjson/msinttypes/inttypes.h \
    thirdparty/include/rapidjson/msinttypes/stdint.h \
    thirdparty/include/rapidjson/allocators.h \
    thirdparty/include/rapidjson/cursorstreamwrapper.h \
    thirdparty/include/rapidjson/document.h \
    thirdparty/include/rapidjson/encodedstream.h \
    thirdparty/include/rapidjson/encodings.h \
    thirdparty/include/rapidjson/filereadstream.h \
    thirdparty/include/rapidjson/filewritestream.h \
    thirdparty/include/rapidjson/fwd.h \
    thirdparty/include/rapidjson/istreamwrapper.h \
    thirdparty/include/rapidjson/memorybuffer.h \
    thirdparty/include/rapidjson/memorystream.h \
    thirdparty/include/rapidjson/ostreamwrapper.h \
    thirdparty/include/rapidjson/pointer.h \
    thirdparty/include/rapidjson/prettywriter.h \
    thirdparty/include/rapidjson/rapidjson.h \
    thirdparty/include/rapidjson/reader.h \
    thirdparty/include/rapidjson/schema.h \
    thirdparty/include/rapidjson/stream.h \
    thirdparty/include/rapidjson/stringbuffer.h \
    thirdparty/include/rapidjson/writer.h \
    thirdparty/include/SDL2/begin_code.h \
    thirdparty/include/SDL2/close_code.h \
    thirdparty/include/SDL2/SDL.h \
    thirdparty/include/SDL2/SDL_assert.h \
    thirdparty/include/SDL2/SDL_atomic.h \
    thirdparty/include/SDL2/SDL_audio.h \
    thirdparty/include/SDL2/SDL_bits.h \
    thirdparty/include/SDL2/SDL_blendmode.h \
    thirdparty/include/SDL2/SDL_clipboard.h \
    thirdparty/include/SDL2/SDL_config.h \
    thirdparty/include/SDL2/SDL_cpuinfo.h \
    thirdparty/include/SDL2/SDL_egl.h \
    thirdparty/include/SDL2/SDL_endian.h \
    thirdparty/include/SDL2/SDL_error.h \
    thirdparty/include/SDL2/SDL_events.h \
    thirdparty/include/SDL2/SDL_filesystem.h \
    thirdparty/include/SDL2/SDL_gamecontroller.h \
    thirdparty/include/SDL2/SDL_gesture.h \
    thirdparty/include/SDL2/SDL_haptic.h \
    thirdparty/include/SDL2/SDL_hints.h \
    thirdparty/include/SDL2/SDL_joystick.h \
    thirdparty/include/SDL2/SDL_keyboard.h \
    thirdparty/include/SDL2/SDL_keycode.h \
    thirdparty/include/SDL2/SDL_loadso.h \
    thirdparty/include/SDL2/SDL_log.h \
    thirdparty/include/SDL2/SDL_main.h \
    thirdparty/include/SDL2/SDL_messagebox.h \
    thirdparty/include/SDL2/SDL_mouse.h \
    thirdparty/include/SDL2/SDL_mutex.h \
    thirdparty/include/SDL2/SDL_name.h \
    thirdparty/include/SDL2/SDL_opengl.h \
    thirdparty/include/SDL2/SDL_opengl_glext.h \
    thirdparty/include/SDL2/SDL_opengles.h \
    thirdparty/include/SDL2/SDL_opengles2.h \
    thirdparty/include/SDL2/SDL_opengles2_gl2.h \
    thirdparty/include/SDL2/SDL_opengles2_gl2ext.h \
    thirdparty/include/SDL2/SDL_opengles2_gl2platform.h \
    thirdparty/include/SDL2/SDL_opengles2_khrplatform.h \
    thirdparty/include/SDL2/SDL_pixels.h \
    thirdparty/include/SDL2/SDL_platform.h \
    thirdparty/include/SDL2/SDL_power.h \
    thirdparty/include/SDL2/SDL_quit.h \
    thirdparty/include/SDL2/SDL_rect.h \
    thirdparty/include/SDL2/SDL_render.h \
    thirdparty/include/SDL2/SDL_revision.h \
    thirdparty/include/SDL2/SDL_rwops.h \
    thirdparty/include/SDL2/SDL_scancode.h \
    thirdparty/include/SDL2/SDL_shape.h \
    thirdparty/include/SDL2/SDL_stdinc.h \
    thirdparty/include/SDL2/SDL_surface.h \
    thirdparty/include/SDL2/SDL_system.h \
    thirdparty/include/SDL2/SDL_syswm.h \
    thirdparty/include/SDL2/SDL_test.h \
    thirdparty/include/SDL2/SDL_test_assert.h \
    thirdparty/include/SDL2/SDL_test_common.h \
    thirdparty/include/SDL2/SDL_test_compare.h \
    thirdparty/include/SDL2/SDL_test_crc32.h \
    thirdparty/include/SDL2/SDL_test_font.h \
    thirdparty/include/SDL2/SDL_test_fuzzer.h \
    thirdparty/include/SDL2/SDL_test_harness.h \
    thirdparty/include/SDL2/SDL_test_images.h \
    thirdparty/include/SDL2/SDL_test_log.h \
    thirdparty/include/SDL2/SDL_test_md5.h \
    thirdparty/include/SDL2/SDL_test_memory.h \
    thirdparty/include/SDL2/SDL_test_random.h \
    thirdparty/include/SDL2/SDL_thread.h \
    thirdparty/include/SDL2/SDL_timer.h \
    thirdparty/include/SDL2/SDL_touch.h \
    thirdparty/include/SDL2/SDL_types.h \
    thirdparty/include/SDL2/SDL_version.h \
    thirdparty/include/SDL2/SDL_video.h \
    thirdparty/include/SDL2/SDL_vulkan.h \
    thirdparty/include/srs_librtmp/srs_librtmp.h \
    samples/define.h \
    samples/mainwindow.h

FORMS += \
    samples/player.ui \
    samples/mainwindow.ui
